name: xstatstests-test
channels:
  - conda-forge
dependencies:
  - python=3.10
  - xarray
  - scipy>=1.8.0
  - numpy
  - dask-core
  - pytest
  - pre-commit
  - pip
  - pip:
    - codecov
    - pytest-cov
